# name: Waka Readme

# on:
#   schedule:
#     - cron: '30 18 * * *'
#   workflow_dispatch:
# jobs:
#   update-readme:
#     name: Update Readme with Metrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: anmol098/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.METRICS_TOKEN   }}
#           SHOW_LINES_OF_CODE : "True"
#           SHOW_PROFILE_VIEWS : "False"
#           SHOW_LOC_CHART : "True"
#           SHOW_TITLE : "True"

name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
          REPOSITORY: <pranay202/pranay202> # optional, By default, it will automatically use the repository who's executing the workflow.
